manifest:
  remotes:
    - name: akadimia
      url-base: https://github.com/liangyongqin

  projects:
    - name: akadimia-zephyr
      remote: akadimia
      revision: main
      path: zephyr
      import: true
      
  self:
    path: .
